source 'https://rubygems.org'

group :development, :test do
  gem 'jekyll', '~> 4.0.0'
  gem 'jekyll-redirect-from', '~> 0.15.0'
  gem 'jekyll-sitemap', '~> 1.3.0'
  gem 'jekyll-toc', '~> 0.3.0.0'
  gem 'scss_lint', '~> 0.54.0'
end
