source 'https://rubygems.org'

group :development, :test do
  gem 'jekyll', '~> 3.5.0'
  gem 'jekyll-redirect-from', '~> 0.13.0'
  gem 'jekyll-sitemap', '~> 1.2.0'
  gem 'jekyll-toc', '~> 0.4.0.0'
  gem 'scss_lint', '~> 0.54.0'
end
